### PR TITLE
Update 'participle' tag in the 'part of speech' of the file README.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by diyclassics** [comment]
It is not clear to me why you want to make this change. Also, this tagset is defined externally by the Perseus NLP team (cf. http://nlp.perseus.tufts.edu/syntax/treebank/1.5/docs/README.txt), so shouldn't be changed.

**Comment by ghost** [comment]
It seems that the participles are marked 'g' and not 't'. I did some tests with verbs and received the following result:

rediens (g-sppamn-)
amatus (g-srppmn-)
habens (g-sppamn-)
dans (g-sppamn-)
cogitans (g-sppamn-)

**Comment by diyclassics** [comment]
Interesting—can you put the code in a gist that I can look at?

**Comment by diyclassics** [comment]
cc: @kylepjohnson 

Also, should note here that the Perseus Latin Treebanks are now on v. 2.1—is it worth dealing with issues on v. 1.5? or should we update the data in this repo to the later version (posted a year ago btw)?

**Comment by kylepjohnson** [comment]
@diyclassics you're right, it would be wise to update to the latest. I have totally lost track of where they were in developing those.

> It seems that the participles are marked 'g' and not 't'. 

@diegocatalao did you get those results from running one of our POS taggers? or are those (apparent) mistakes in the treebank data?

**Comment by ghost** [comment]
@kylepjohnson 
> @diegocatalao did you get those results from running one of our POS taggers? or are those (apparent) mistakes in the treebank data?

I'm using CorpusImporter to get all corpus and CollatinusDecliner for declensions:

['latin_text_perseus', 'latin_treebank_perseus', 'latin_text_latin_library', 'phi5', 'phi7', 'latin_proper_names_cltk', 'latin_models_cltk', 'latin_pos_lemmata_cltk', 'latin_treebank_index_thomisticus', 'latin_lexica_perseus', 'latin_training_set_sentence_cltk', 'latin_word2vec_cltk', 'latin_text_antique_digiliblt', 'latin_text_corpus_grammaticorum_latinorum', 'latin_text_poeti_ditalia']

@diyclassics 
> Interesting—can you put the code in a gist that I can look at?
```
class Support:
	def update_base(self):
                # self.corpora is the list of databases
		for corpus in self.corpora:
		     self.corpus_importer.import_corpus(corpus)
```
```
def __init__(self, word):
	self.word = word

	self.decliner = CollatinusDecliner()
	self.declined = self.decliner.decline(self.word)
```

When did I download the database it came in the old version?

**Comment by kylepjohnson** [comment]
@diyclassics What do you say we put this on our agenda for when we are together with the Perseus team. A few things I'd like clarity on:
* Who is responsible for the treebanks and what are the plans for their development?
* What software and algos should we be using and making available? I am happy enough with the old NLTK POS models I made. And your backoff lemmatizer uses this same particular repo, too, right?

@diegocatalao It helps knowing that you're using Collatinus. This uses a different training set and, so it seems, slightly different tags.

* Collatinus docs: http://docs.cltk.org/en/latest/latin.html
* Collatinus source data: https://github.com/biblissima/collatinus/tree/master/bin/data

If you want to use the POS tagger made from the data in this repo, here are the directions: http://docs.cltk.org/en/latest/latin.html#pos-tagging

**Comment by kylepjohnson** [comment]
@diegocatalao One other thing, the Collatinus data that your code uses is here, in our Latin models repo: https://github.com/cltk/latin_models_cltk/tree/master/lemmata/collatinus

**Comment by ghost** [comment]
>  It helps knowing that you're using Collatinus. This uses a different training set and, so it seems, slightly different tags.

@kylepjohnson @diyclassics Now everything was clear. I imported all items on the list and, it seems, they are Collatinus tags. Thanks for the clarification. Sorry for pull request. I will try the POS tagger.

**Pull request closed without merging**
